package com.tpe.dpsolver.client.parser;

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface DCParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int NEG = 6;
  /** RegularExpression Id. */
  int CORTE = 7;
  /** RegularExpression Id. */
  int CONJ = 8;
  /** RegularExpression Id. */
  int DISY = 9;
  /** RegularExpression Id. */
  int IMPL = 10;
  /** RegularExpression Id. */
  int IFF = 11;
  /** RegularExpression Id. */
  int LITERAL = 12;
  /** RegularExpression Id. */
  int LP = 13;
  /** RegularExpression Id. */
  int RP = 14;
  /** RegularExpression Id. */
  int LBRACE = 15;
  /** RegularExpression Id. */
  int RBRACE = 16;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"--\"",
    "\"-\"",
    "\";\"",
    "<CONJ>",
    "<DISY>",
    "<IMPL>",
    "<IFF>",
    "<LITERAL>",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
  };

}
